if(FDATE_ENABLE_TESTING)

  # Add Catch2 using CPM
  cpmaddpackage(
    NAME
    Catch2
    GITHUB_REPOSITORY
    catchorg/Catch2
    VERSION
    3.8.1
    OPTIONS
    "CATCH_BUILD_TESTS OFF"
    "CATCH_BUILD_EXAMPLES OFF"
    "CATCH_BUILD_EXAMPLES OFF"
    "CATCH_BUILD_TESTS OFF"
    "CATCH_INSTALL_DOCS OFF"
    "CATCH_INSTALL_HELPERS OFF"
    "CATCH_INSTALL_PDB OFF"
    "CATCH_INSTALL_PDB OFF"
    "CATCH_INSTALL_TESTS OFF"
    "CATCH_NO_UNPREFIXED_TEST_CASES ON")

endif()
